name: flutter_tools
version: 0.0.38
description: Tools for building Flutter applications
homepage: http://flutter.io
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  archive: ^1.0.20
  args: ^0.13.4
  crypto: 0.9.2
  file: ^0.1.0
  http: ^0.11.3
  json_schema: ^1.0.3
  mustache4dart: ^1.0.0
  package_config: ^0.1.3
  path: ^1.3.0
  pub_semver: ^1.0.0
  stack_trace: ^1.4.0
  yaml: ^2.1.3
  xml: ^2.4.1

  flx:
    path: ../flx

  test: 0.12.13 # see note below
  analyzer: '0.27.2' # see note below

# A note about 'test':
# We depend on very specific internal implementation details of the
# 'test' package, which change between versions, so here we pin it
# precisely.

# A note about 'analyzer':
# We don't actually depend on 'analyzer', but 'test' does. We aren't
# compatible with some older versions of 'analyzer'. We lie here,
# saying we do depend on it, so that we constrain the version that
# 'test' will get to a version that we'll probably be ok with. (This
# is why there's no upper bound on our dependency.)
# See also https://github.com/dart-lang/pub/issues/1356

dev_dependencies:
  mockito: ^0.11.0

# Exclude this package from the hosted API docs.
dartdoc:
  nodoc: true
