name: material_gallery
dependencies:
  intl: '>=0.12.4+2 <0.13.0'
  collection: '>=1.4.0 <2.0.0'
  string_scanner: '0.1.4+1'

  flutter:
    path: ../../packages/flutter
  flutter_sprites:
    path: ../../packages/flutter_sprites
  flutter_markdown:
    path: ../../packages/flutter_markdown
  flutter_gallery_assets: '0.0.13'
