name: flx
version: 0.0.10
author: Flutter Authors <flutter-dev@googlegroups.com>
description: Library for dealing with Flutter bundle (.flx) files
homepage: https://github.com/flutter/flutter/tree/master/packages/flx
dependencies:
  bignum: ^0.1.0
  asn1lib: ^0.4.1
  pointycastle: 0.10.0
  crypto: 0.9.2

environment:
  sdk: '>=1.12.0 <2.0.0'

dev_dependencies:
  flutter_test:
    path: ../flutter_test

# Exclude this package from the hosted API docs.
dartdoc:
  nodoc: true
