name: newton
description: Simple Physics Simulations for Dart
version: 0.1.5
author: Flutter Authors <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/flutter/tree/master/packages/newton
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  flutter_test:
    path: ../flutter_test
